// Contactos
export const CONTACTO_ACTUAL = 'CONTACTO_ACTUAL';
export const ACTUALIZAR_CONTACTO = 'ACTUALIZAR_CONTACTO';

// Compañías
export const FORMULARIO_COMPANY = 'FORMULARIO_COMPANY';
export const OBTENER_COMPANIES = 'OBTENER_COMPANIES';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const AGREGAR_COMPANIA = 'AGREGAR_COMPANIA';
export const ELIMINAR_COMPANIA = 'ELIMINAR_COMPANIA';
export const COMPANY_SELECCIONADA = 'COMPANY_SELECCIONADA';
export const ACTUALIZAR_COMPANY = 'ACTUALIZAR_COMPANY';

// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// Registro, Login y Logout
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';